# https://travis-ci.org/orbingol/NURBS-Python

dist: bionic
sudo: false

# enable x server
services:
  - xvfb

# apt install the required packages
addons:
  apt:
    packages:
      - libgtk2.0-0
      - libxss1
      - libgconf-2-4
      - libnss3
      - libasound2
      - poppler-utils

# branches to build
branches:
  only:
    - 6.x-dev # v6.x development
    - 5.x-dev # v5.x development
    - 6.x  # v6.x series
    - 5.x  # v5.x series
    - 4.x  # v4.x series
    - 3.x  # v3.x series
    - 2.x  # v2.x series
    - master  # master branch
    - travisci-testing  # CI testing

# environmental variables
env:
  - MPLBACKEND=Agg

# Ref: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - sudo apt update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # useful for debugging any issues with conda
  - conda info -a
  # install dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy matplotlib plotly vtk cython pytest pytest-cov codecov
  # activate test environment
  - conda activate test-environment
  # install plotly dependencies
  - conda install psutil requests
  - conda install -c plotly plotly-orca
  # install packages
  - python setup.py develop
  - python setup_core.py build_ext --inplace

# test geomdl.core installation
before_script:
  - python -c "from geomdl.core import NURBS; ns = NURBS.Surface(); print(ns.name)"

# run pytest
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pytest --cov=./;
    else
      pytest;
    fi

# post-testing tasks
after_script:
  # run codecov
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      codecov -e $TRAVIS_PYTHON_VERSION;
    fi
  # run performance scripts
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      python .travisci/curve_sequential_pure.py;
      python .travisci/curve_sequential_core.py;
    fi
