# https://travis-ci.org/orbingol/NURBS-Python

dist: bionic
sudo: false

language: python
cache: pip

# branches to build
branches:
  only:
    - 6.x-dev # v6.x development
    - 5.x-dev # v5.x development
    - 6.x  # v6.x series
    - 5.x  # v5.x series
    - 4.x  # v4.x series
    - 3.x  # v3.x series
    - 2.x  # v2.x series
    - master  # master branch
    - travisci-testing  # CI testing

# build matrix
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36,test

    - python: 3.7
      env: TOXENV=py37,test

    - python: 3.8
      env: TOXENV=py38,test,codecov

    - name: "Performance testing on Python 3.6"
      python: 3.6
      env: TOXENV=py36,performance-full
      if: branch = master OR branch = travisci-testing

# install packages
install:
  - npm install -g npm  # for plotly static image export
  - python -m pip install --upgrade pip  # upgrade pip
  - pip install tox

# run tox
script:
  - tox
