# https://travis-ci.org/orbingol/NURBS-Python

dist: bionic
sudo: false

# enable x server
services:
  - xvfb

# apt install the required packages
addons:
  apt:
    packages:
      - libgtk2.0-0
      - libxss1
      - libgconf-2-4
      - libnss3
      - libasound2
      - poppler-utils

language: python
cache: pip

# branches to build
branches:
  only:
    - 6.x-dev # v6.x development
    - 5.x-dev # v5.x development
    - 6.x  # v6.x series
    - 5.x  # v5.x series
    - 4.x  # v4.x series
    - 3.x  # v3.x series
    - 2.x  # v2.x series
    - master  # master branch
    - travisci-testing  # CI testing

# build matrix
matrix:
  include:
    - os: linux
      arch: amd64
      python: 3.6
      env: TOXENV=py36,test

    - os: linux
      arch: amd64
      python: 3.7
      env: TOXENV=py37,test

    - os: linux
      arch: amd64
      python: 3.8
      env: TOXENV=py38,test,codecov

    - name: "Performance testing on Python 3.6"
      os: linux
      arch: amd64
      python: 3.6
      env: TOXENV=py36,performance-full
      if: branch = master OR branch = travisci-testing

# install packages
install:
  - pip install tox

# run tox
script:
  - tox
